version: "3.8"
services:
  rust:
    build: .
    ports:
      - 8080:8080
    command: "sh -c 'cd hello-webpack-template && npm start'"
    volumes:
      - .:/usr/hello-wasm-bindgen

  node:
    build: front
    volumes:
      - .:/usr/hello-wasm-bindgen
